grails-app/controllers/AuthController.groovy
import org.apache.shiro.SecurityUtils
import org.apache.shiro.authc.AuthenticationException
import org.apache.shiro.authc.UsernamePasswordToken
import org.apache.shiro.web.util.SavedRequest
import org.apache.shiro.web.util.WebUtils
import org.apache.shiro.grails.ConfigUtils

class AuthController {
    def shiroSecurityManager

    def index = { redirect(action: "login", params: params) }

    def login = {
        return [username: params.username, rememberMe: (params.rememberMe != null), targetUri: params.targetUri]
    }

    def signIn = {
        def authToken = new UsernamePasswordToken(params.username, params.password as String)

        // Support for "remember me"
        if (params.rememberMe) {
            authToken.rememberMe = true
        }

        // If a controller redirected to this page, redirect back
        // to it. Otherwise redirect to the root URI.
        def targetUri = params.targetUri ?: "/admin"

        // Handle requests saved by Shiro filters.
        def savedRequest = WebUtils.getSavedRequest(request)
        if (savedRequest) {
            targetUri = savedRequest.requestURI - request.contextPath
            if (savedRequest.queryString) targetUri = targetUri + '?' + savedRequest.queryString
        }

        try {
            // Perform the actual login. An AuthenticationException
            // will be thrown if the username is unrecognised or the
            // password is incorrect.
            SecurityUtils.subject.login(authToken)

            flash.put("login", true)
            log.info "Redirecting to '${targetUri}'."
            redirect(uri: targetUri)
        }
        catch (AuthenticationException ex) {
            // Authentication failed, so display the appropriate message
            // on the login page.
            log.info "Authentication failure for user '${params.username}'."
            flash.message = message(code: "login.failed")

            // Keep the username and "remember me" setting so that the
            // user doesn't have to enter them again.
            def m = [username: params.username]
            if (params.rememberMe) {
                m["rememberMe"] = true
            }

            // Remember the target URI too.
            if (params.targetUri) {
                m["targetUri"] = params.targetUri
            }

            // Now redirect back to the login page.
            redirect(action: "login", params: m)
        }
    }

    def signOut = {
        // Log the user out of the application.
        def principal = SecurityUtils.subject?.principal
        SecurityUtils.subject?.logout()
        // For now, redirect back to the home page.
        if (ConfigUtils.getCasEnable() && ConfigUtils.isFromCas(principal)) {
            redirect(uri: ConfigUtils.getLogoutUrl())
        } else {
            redirect(uri: "/")
        }
        ConfigUtils.removePrincipal(principal)
    }

    def unauthorized = {
        render "You do not have permission to access this page."
    }
}

grails-app/views/layouts/grails-main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'grails-main.css')}" type="text/css">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css">
		<g:layoutHead/>
		<r:layoutResources />
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><img src="${resource(dir: 'images', file: 'grails_logo.png')}" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
		<g:javascript library="application"/>
		<r:layoutResources />
	</body>
</html>

grails-app/views/layouts/main.gsp
<%@ page import="org.apache.shiro.SecurityUtils" %>
<%--
  Created by IntelliJ IDEA.
  User: Joseph Lee <josel@pdx.edu>
  Date: 7/17/13
  Time: 1:00 AM
--%>

<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><g:layoutTitle default="GenBank-Query"/></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <r:require module="bootstrap"/>

    <link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
    <link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
    <link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">

    <%--
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css">
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'main.css')}" type="text/css">
    --%>

    <r:layoutResources />
    <g:layoutHead/>

</head>

<body style="background-color: #ffffff">

<%--
    Upload Modal
--%>
<div id="upload" class="modal fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Add Sequences to Analyze</h3>
    </div>
    <div class="modal-body">
        <g:uploadForm action="upload" class="form-horizontal" name="upload-form">
            <div id="upload-form-list"></div>

            <div class="add-upload" style="text-align: center">
                <input type="button" id="upload" class="btn add-seq" value="Add Custom Sequence"/>
                <input type="button" id="genbank" class="btn add-seq" value="Add GenBank Sequence"/>
                <input type="submit" id="upload-submit" class="btn btn-submit" disabled/>
            </div>
        </g:uploadForm>
    </div>
</div>

<%-- Top-level div --%>
<div class="container-narrow" id="main-body">
    <%--
        Navigation Bar
    --%>
    <div class="masthead">
        <ul class="nav nav-pills pull-right">

            <li class="active"><a href="#" id="upload-nav">Analyze Sequences</a></li>

            <g:if test="${SecurityUtils.subject.isPermitted("admin")}">
                <li class="dropdown">
                    <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" href="#">
                        admin
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                        <li>
                            <g:link controller="admin" action="index">Admin Page</g:link>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <g:link controller="auth" action="signOut">Log Out</g:link>
                        </li>
                    </ul>
                </li>
            </g:if>
            <g:else>
                <li>
                    <g:link controller="auth" action="login">Log in</g:link>
                </li>
            </g:else>

            <li>
                <form class="navbar-search">
                    <input type="text" class="search-query" id="quick-search"
                           placeholder="Organism Quick Search" autocomplete="off">
                </form>
            </li>
        </ul>
        <h1 class="muted">
            <a href="/webapp">GenBank-Query</a>
            <a href="http://github.com/phenylalanine/genbank-query">
            <r:img uri="/images/GitHub-Mark-32px.png" height="24px" width="24px" /></a>
        </h1>
    </div>

    <hr>

    <g:layoutBody/>

    <p>Copyright © 2013 <a href="http://github.com/phenylalanine">Phenylalanine</a> &
        <a href="http://www.pdx.edu/extreme-environments/">Center for Life in Extreme Environments, Portland State University</a><br/>
    Content may be used and distributed under the <a href="http://en.wikipedia.org/wiki/MIT_License">MIT License</a>
    unless otherwise noted.</p>
</div>



<r:require module="mainpage" />
<r:layoutResources />



</body>
</html>

grails-app/views/layouts/upload.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><g:layoutTitle default="Grails"/></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
    <link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
    <link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'upload.css')}" type="text/css">
    <!--link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css"-->
    <r:require modules="bootstrap"/>
    <g:layoutHead/>
    <r:layoutResources />
</head>

<body style="background-color: #fff">
<div class="wrap">
    <div class="container" style="background-color: #ffffff; margin-top: 60px">
        <div class="page-header">
            <h1>Upload Sequence</h1>
        </div>
        <div id="form-upload">
            <g:layoutBody/>
        </div>
    </div>
    <g:javascript library="application"/>
    <r:layoutResources />

</div>
</body>
</html>